### ISSUE TITLE
driver should fail gracefully instead of silently on connection failure

### ISSUE THREAD

**Issue by ojura** [larics/sicks300#1]

**Comment by ojura** [comment]
e.g. when ES522.sh has not been executed

**Comment by dmiklic** [comment]
I have merged some upstream changes that might have fixed this. At least I'm getting a verbose connection error now when there's no ES522 converter connected. @ojura please test again on the robot.

**Comment by ojura** [comment]
Tried out the brainbox and s300_professional branches, both fail with
`[FATAL] [1481647663.535468347]: ASSERTION FAILED
	file = /home/larics/catkin_ws/src/sicks300/src/sicks300.cpp
	line = 108
	cond = beams_to_skip.getType() == XmlRpc::XmlRpcValue::TypeArray`

Current behaviour of the `master` branch: 
If the driver node is run without previously creating the serial ports, the following message is output, and that's okay (perhaps it should be converted into a ROS_ERROR message):
`SerialCommS300: unable to open serial port /dev/ES522_1`

However, if the sensor gets disconnected after a successful initial connection has been established, we have silent failure.

**Comment by ojura** [comment]
Fixed in 65ebaa3f9d27e8ae187e4fe6c979d84bec2722f9
